name: invokex

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2.5-management
    hostname: invokex-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=invokex
      - RABBITMQ_DEFAULT_PASS=admin
