#!/bin/sh
# This is a special script that will initialize the system; the userspace entrypoint.
# Specifically, this will be PID 1 and it is what will set up userspace and start the actual system.
# This script will be placed in the rootfs so the Linux kernel can use it during its boot sequence.

# Mount kernel-provided virtual filesystems.
mount -t proc none /proc    # process list, memory info, cpu info, kernel parameters, etc
mount -t sysfs none /sys    # provides network interfaces, block devices, kernel subsystems, etc
mount -t devtmpfs none /dev # kernel-managed device nodes - disk access, console output, etc
mount -t tmpfs none /run    # RAM-backed temporary filesystem, for sockets, PID files, etc

# Basic environment set-up.
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo "rootfs booted"

# Start shell as PID 1 (replaces this wrapper).
exec /bin/sh
